# Generated by Django 4.2.5 on 2023-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo_path', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара')),
            ],
        ),
    ]
